### ISSUE TITLE
error: 'NoneType' object has no attribute 'w'

### ISSUE THREAD

**Issue by AjayGarad** [nadirhamid/binner#1]
Hi nadirhamid,
I was trying your algorithm "multi", but got error as follows:

/binner-master/bin$ python binner-cli --bins '[{ "title": "test", "w": 100000, "h": 10000, "d": 100, "weight": 20, "id": 1, "max_weight": 1000 }, { "title": "test", "w": 100000, "h": 10000, "d": 100, "weight": 20, "id": 1, "max_weight": 1000 }]' --items '[{ "title": "test", "w": 50, "h": 50, "d": 50, "q": 2, "weight": 200, "id":202 }, { "title": "test", "w": 50, "h": 50, "d": 100, "weight": 20, "id": 2, "max_weight": 1000 }]' --algorithm "multi"
2017-11-02 21:27:01,175 Registering Entity
2017-11-02 21:27:01,175 {u'd': 100, u'weight': 20, u'title': u'test', u'h': 10000, u'w': 100000, u'id': 1, u'max_weight': 1000}
2017-11-02 21:27:01,175 Registering Entity
2017-11-02 21:27:01,175 {u'd': 100, u'weight': 20, u'title': u'test', u'h': 10000, u'w': 100000, u'id': 1, u'max_weight': 1000}
2017-11-02 21:27:01,176 Registering Entity
2017-11-02 21:27:01,176 {u'd': 50, u'weight': 200, u'title': u'test', u'h': 50, u'q': 2, u'w': 50, u'id': 202}
2017-11-02 21:27:01,176 Registering Entity
2017-11-02 21:27:01,176 {u'd': 100, u'weight': 20, u'title': u'test', u'h': 50, u'w': 50, u'id': 2, u'max_weight': 1000}
2017-11-02 21:27:01,176 Entering Algorithm MULTI
2017-11-02 21:27:01,176 Packing Bin #1
2017-11-02 21:27:01,176 CHECKING SPACE X: 0, MX: 0, Y: 0, MY: 50, Z: 50, MZ: 50
2017-11-02 21:27:01,176 adding a box at: x: 1, mx: 51, y: 0, my: 51, z: 0, mz: 50
Traceback (most recent call last):
  File "binner-cli", line 5, in <module>
    RuntimeCLI( sys.argv )
  File "/usr/local/lib/python2.7/dist-packages/binner/runtime_cli.py", line 14, in __init__
    self.initv2( self.args )
  File "/usr/local/lib/python2.7/dist-packages/binner/runtime_cli.py", line 48, in initv2
    self.run( result )
  File "/usr/local/lib/python2.7/dist-packages/binner/runtime_cli.py", line 72, in run
    binner_algo.run()
  File "/usr/local/lib/python2.7/dist-packages/binner/algo_multi.py", line 69, in run
    if not bin.can_fit( item ):
  File "/usr/local/lib/python2.7/dist-packages/binner/entity_bin.py", line 202, in can_fit
    item_max_x = (max_x+item.w)
AttributeError: 'NoneType' object has no attribute 'w'

can you tell me what can i do to take out this error?

**Comment by teknix** [comment]
@AjayGarad how did you solve this issue?
